name: Release Build
on:
  push:
    branches:
      - main
      - v0.1.x
  pull_request:
    branches:
      - main
      - v0.1.x
jobs:
  release-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [
          ubuntu-latest,
          macos-latest,
          windows-latest,
        ]
        toolchain: [
          stable,
        ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Sqlcipher Linux
        if: ${{ runner.os == 'Linux' }}
        run: sudo apt-get install libsqlcipher-dev

      - name: Install Sqlcipher MacOs
        if: ${{ runner.os == 'macOs' }}
        run: brew install sqlcipher

      - name: Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}

      - name: Build Release
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
